name: Build Wight Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Godot
      id: cache-godot
      uses: actions/cache@v3
      with:
        path: ~/godot
        key: godot-4.2.2-linux
        
    - name: Download Godot
      if: steps.cache-godot.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/godot
        cd ~/godot
        wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
        unzip Godot_v4.2.2-stable_linux.x86_64.zip
        chmod +x Godot_v4.2.2-stable_linux.x86_64
        
    - name: Download Android Export Templates
      run: |
        cd ~/godot
        wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
        unzip Godot_v4.2.2-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/4.2.2.stable
        mv ~/.local/share/godot/export_templates/4.2.2.stable/templates/* ~/.local/share/godot/export_templates/4.2.2.stable/
        
    - name: Setup Godot Export Settings
      run: |
        mkdir -p ~/.config/godot
        echo '[gd_resource type="EditorSettings" format=3]
        [resource]
        export/android/android_sdk_path = "'$ANDROID_HOME'"
        export/android/debug_keystore = "'$HOME'/.android/debug.keystore"
        export/android/debug_keystore_user = "androiddebugkey"
        export/android/debug_keystore_pass = "android"' > ~/.config/godot/editor_settings-4.tres
        
    - name: Generate Debug Keystore
      run: |
        mkdir -p ~/.android
        keytool -genkeypair -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Debug,O=Android,C=US"
        
    - name: Build APK
      run: |
        cd ${{ github.workspace }}/WightAndroid
        mkdir -p builds
        ~/godot/Godot_v4.2.2-stable_linux.x86_64 --headless --export-release "Android" builds/WightAndroid.apk
        
    - name: Create Release Zip
      run: |
        mkdir -p release
        cp WightAndroid/builds/WightAndroid.apk release/
        cp WightAndroid/ANDROID_BUILD_GUIDE.md release/
        cp WightAndroid/CONVERSION_SUMMARY.md release/
        cd release
        zip -r WightAndroid-v1.0.zip *
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WightAndroid-APK
        path: release/WightAndroid-v1.0.zip
        retention-days: 90
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Wight Android v1.0.${{ github.run_number }}
        body: |
          ## 📱 Wight AI Companion - Android APK
          
          Fully offline AI companion with consciousness, emotions, and learning capabilities.
          
          ### 🎯 Features
          - Complete AI consciousness with 10 emotions
          - Persistent memory and learning
          - 3D creative sandbox
          - Voice communication
          - Touch-optimized mobile interface
          - Fully offline operation
          
          ### 📲 Installation
          1. Download `WightAndroid.apk`
          2. Enable "Unknown Sources" in Android settings
          3. Install APK on your Android device
          4. Launch and start chatting with Wight!
          
          ### 📋 Requirements
          - Android 7.0+ (API 24+)
          - ARM64 device architecture
          - ~50MB storage space
          - Microphone permission for voice features
          
        files: |
          release/WightAndroid-v1.0.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}